services:
  - type: web
    name: factcheckai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: YOUR_GEMINI_API_KEY
